package xyz.jpenilla.pluginbase.legacy.environment;

import static xyz.jpenilla.pluginbase.legacy.environment.MinecraftRelease.minecraftRelease;
import static xyz.jpenilla.pluginbase.legacy.environment.MinecraftRelease.oldSchemaRelease;

public final class MinecraftReleases {
    private MinecraftReleases() {
    }

    public static final MinecraftRelease v1_7_10 = oldSchemaRelease(7, 10);
    public static final MinecraftRelease v1_8 = oldSchemaRelease(8, 0);
    public static final MinecraftRelease v1_8_1 = oldSchemaRelease(8, 1);
    public static final MinecraftRelease v1_8_2 = oldSchemaRelease(8, 2);
    public static final MinecraftRelease v1_8_3 = oldSchemaRelease(8, 3);
    public static final MinecraftRelease v1_8_4 = oldSchemaRelease(8, 4);
    public static final MinecraftRelease v1_8_5 = oldSchemaRelease(8, 5);
    public static final MinecraftRelease v1_8_6 = oldSchemaRelease(8, 6);
    public static final MinecraftRelease v1_8_7 = oldSchemaRelease(8, 7);
    public static final MinecraftRelease v1_8_8 = oldSchemaRelease(8, 8);
    public static final MinecraftRelease v1_8_9 = oldSchemaRelease(8, 9);
    public static final MinecraftRelease v1_9 = oldSchemaRelease(9, 0);
    public static final MinecraftRelease v1_9_1 = oldSchemaRelease(9, 1);
    public static final MinecraftRelease v1_9_2 = oldSchemaRelease(9, 2);
    public static final MinecraftRelease v1_9_3 = oldSchemaRelease(9, 3);
    public static final MinecraftRelease v1_9_4 = oldSchemaRelease(9, 4);
    public static final MinecraftRelease v1_10 = oldSchemaRelease(10, 0);
    public static final MinecraftRelease v1_10_1 = oldSchemaRelease(10, 1);
    public static final MinecraftRelease v1_10_2 = oldSchemaRelease(10, 2);
    public static final MinecraftRelease v1_11 = oldSchemaRelease(11, 0);
    public static final MinecraftRelease v1_11_1 = oldSchemaRelease(11, 1);
    public static final MinecraftRelease v1_11_2 = oldSchemaRelease(11, 2);
    public static final MinecraftRelease v1_12 = oldSchemaRelease(12, 0);
    public static final MinecraftRelease v1_12_1 = oldSchemaRelease(12, 1);
    public static final MinecraftRelease v1_12_2 = oldSchemaRelease(12, 2);
    public static final MinecraftRelease v1_13 = oldSchemaRelease(13, 0);
    public static final MinecraftRelease v1_13_1 = oldSchemaRelease(13, 1);
    public static final MinecraftRelease v1_13_2 = oldSchemaRelease(13, 2);
    public static final MinecraftRelease v1_14 = oldSchemaRelease(14, 0);
    public static final MinecraftRelease v1_14_1 = oldSchemaRelease(14, 1);
    public static final MinecraftRelease v1_14_2 = oldSchemaRelease(14, 2);
    public static final MinecraftRelease v1_14_3 = oldSchemaRelease(14, 3);
    public static final MinecraftRelease v1_14_4 = oldSchemaRelease(14, 4);
    public static final MinecraftRelease v1_15 = oldSchemaRelease(15, 0);
    public static final MinecraftRelease v1_15_1 = oldSchemaRelease(15, 1);
    public static final MinecraftRelease v1_15_2 = oldSchemaRelease(15, 2);
    public static final MinecraftRelease v1_16 = oldSchemaRelease(16, 0);
    public static final MinecraftRelease v1_16_1 = oldSchemaRelease(16, 1);
    public static final MinecraftRelease v1_16_2 = oldSchemaRelease(16, 2);
    public static final MinecraftRelease v1_16_3 = oldSchemaRelease(16, 3);
    public static final MinecraftRelease v1_16_4 = oldSchemaRelease(16, 4);
    public static final MinecraftRelease v1_16_5 = oldSchemaRelease(16, 5);
    public static final MinecraftRelease v1_17 = oldSchemaRelease(17, 0);
    public static final MinecraftRelease v1_17_1 = oldSchemaRelease(17, 1);
    public static final MinecraftRelease v1_18 = oldSchemaRelease(18, 0);
    public static final MinecraftRelease v1_18_1 = oldSchemaRelease(18, 1);
    public static final MinecraftRelease v1_18_2 = oldSchemaRelease(18, 2);
    public static final MinecraftRelease v1_19 = oldSchemaRelease(19, 0);
    public static final MinecraftRelease v1_19_1 = oldSchemaRelease(19, 1);
    public static final MinecraftRelease v1_19_2 = oldSchemaRelease(19, 2);
    public static final MinecraftRelease v1_19_3 = oldSchemaRelease(19, 3);
    public static final MinecraftRelease v1_19_4 = oldSchemaRelease(19, 4);
    public static final MinecraftRelease v1_20 = oldSchemaRelease(20, 0);
    public static final MinecraftRelease v1_20_1 = oldSchemaRelease(20, 1);
    public static final MinecraftRelease v1_20_2 = oldSchemaRelease(20, 2);
    public static final MinecraftRelease v1_20_3 = oldSchemaRelease(20, 3);
    public static final MinecraftRelease v1_20_4 = oldSchemaRelease(20, 4);
    public static final MinecraftRelease v1_20_5 = oldSchemaRelease(20, 5);
    public static final MinecraftRelease v1_20_6 = oldSchemaRelease(20, 6);
    public static final MinecraftRelease v1_21 = oldSchemaRelease(21, 0);
    public static final MinecraftRelease v1_21_1 = oldSchemaRelease(21, 1);
    public static final MinecraftRelease v1_21_2 = oldSchemaRelease(21, 2);
    public static final MinecraftRelease v1_21_3 = oldSchemaRelease(21, 3);
    public static final MinecraftRelease v1_21_4 = oldSchemaRelease(21, 4);
    public static final MinecraftRelease v1_21_5 = oldSchemaRelease(21, 5);
    public static final MinecraftRelease v1_21_6 = oldSchemaRelease(21, 6);
    public static final MinecraftRelease v1_21_7 = oldSchemaRelease(21, 7);
    public static final MinecraftRelease v1_21_8 = oldSchemaRelease(21, 8);
    public static final MinecraftRelease v1_21_9 = oldSchemaRelease(21, 9);
    public static final MinecraftRelease v1_21_10 = oldSchemaRelease(21, 10);
    public static final MinecraftRelease v1_21_11 = oldSchemaRelease(21, 11);
    public static final MinecraftRelease v26_1 = minecraftRelease(26, 1, 0);
    public static final MinecraftRelease v26_1_1 = minecraftRelease(26, 1, 1);
}
